# Generated by Django 5.1.4 on 2025-03-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_result_department_result_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
