# Generated by Django 5.1.4 on 2025-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='subject_teachers_set', to='core.classgroup'),
        ),
    ]
